[build]
  publish = "build"
  command = "npm run build && cp functions-package.json netlify/functions/package.json"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_VERSION = "9.6.7"

[functions]
  node_bundler = "zisi"
  included_files = ["netlify/functions/**"]

# Auth routes - MUST be before catch-all  
[[redirects]]
  from = "/auth/*"
  to = "/.netlify/functions/auth/:splat"
  status = 200
  force = true

# API routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

# Test functions
[[redirects]]
  from = "/test-working"
  to = "/.netlify/functions/working"
  status = 200

# Catch-all for React app (MUST be last)
[[redirects]]
  from = "/*"
  to = "/index.html"  
  status = 200