[build]
  publish = "build"
  command = "npm run build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

# Frontend Routes only - test functions directly
[[redirects]]
  from = "/*"
  to = "/index.html"  
  status = 200