[build]
  publish = "build"
  command = "npm run build"
  functions = "netlify/functions"

# API Routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Auth Routes  
[[redirects]]
  from = "/auth/*"
  to = "/.netlify/functions/auth/:splat"
  status = 200

# Test Route
[[redirects]]
  from = "/simple"
  to = "/.netlify/functions/simple"
  status = 200

# Frontend Routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  CI = "false"