[build]
  publish = "build"
  command = "npm run build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

# Auth routes - MUST be before catch-all  
[[redirects]]
  from = "/auth/*"
  to = "/.netlify/functions/auth/:splat"
  status = 200
  force = true

# API routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

# Test functions
[[redirects]]
  from = "/test-working"
  to = "/.netlify/functions/working"
  status = 200

# Catch-all for React app (MUST be last)
[[redirects]]
  from = "/*"
  to = "/index.html"  
  status = 200