[build]
  publish = "build"
  command = "npm run build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

# Function routes
[[redirects]]
  from = "/auth/*"
  to = "/.netlify/functions/auth/:splat"
  status = 200

[[redirects]]
  from = "/test"
  to = "/.netlify/functions/test"
  status = 200

# React app catch-all
[[redirects]]
  from = "/*"
  to = "/index.html"  
  status = 200